### ISSUE TITLE
libgit 0.28 compatible release

### ISSUE THREAD

**Issue by 0-wiz-0** [libgit2/pygit2#878] opened 2019-02-24 10:23 UTC
Please release a version of pygit2 that's compatible with the current latest release of libgit, 0.28.1.
Thanks.

**Comment by mwilck** [comment] 2019-03-07 09:24
I'm interested in this one too. The recent update of libgit2 on openSUSE Factory has broken pygit2. I'd appreciate some information when a 0.28.0-compatible release might be available, or what changes are anticipated to make pygit2 work with libgit2 0.28.0.

**Comment by jayvdb** [comment] 2019-03-07 13:22
The repo here is now using 0.28 since https://github.com/libgit2/pygit2/commit/8dabd78fae7ad7c0de342f2ba5014dceee5ac226, however 11 tests are failing as seen at https://travis-ci.org/libgit2/pygit2/jobs/501118496

These failures correlate with breaking changes in the 0.28 relnotes at https://github.com/libgit2/libgit2/blob/master/docs/changelog.md

**Comment by jdavid** [comment] 2019-03-07 16:45
There's 1 failure left now:

```
E       GitError: failed to insert entry: invalid object specified - .gitignore
```

If someone wants to give it a try :wink:

**Comment by webknjaz** [comment] 2019-03-07 17:19
I don't have time to dig into this myself but just to confirm: are you going to create a release once the CI is green?

**Comment by jdavid** [comment] 2019-03-07 20:11
yes, there's nothing else blocking the release I think

**Comment by jdavid** [comment] 2019-03-09 17:54
This failure is actually a regression in libgit2, see https://github.com/libgit2/libgit2/issues/5015

@webknjaz @imbuedHope  The tests in AppVeyor are failing as well for a different reason, since PR #884 was merged, see https://ci.appveyor.com/project/jdavid/pygit2/branch/master/job/mwf4pj02fe0yubwk#L7514

```
test\utils.py:42: in <module>
    import pygit2
pygit2\__init__.py:269: in <module>
    settings = Settings()
pygit2\settings.py:65: in __init__
    self._default_tls_verify_paths.capath,
pygit2\settings.py:151: in set_ssl_cert_locations
    option(GIT_OPT_SET_SSL_CERT_LOCATIONS, ssl_cert_file, ssl_cert_dir)
E   GitError: TLS backend doesn't support certificate locations

```

**Comment by webknjaz** [comment] 2019-03-09 17:55
@jdavid I think, this should probably be turned off under Windows. Another option would be building Windows wheels against OpenSSL.

**Comment by jdavid** [comment] 2019-03-09 17:58
@fourplusone

**Comment by webknjaz** [comment] 2019-03-09 18:00
Another solution would be wrapping things with try/except and ignoring just this specific error.

**Comment by webknjaz** [comment] 2019-03-09 18:02
I think, try/except in the initializer is all we need.

**Comment by webknjaz** [comment] 2019-03-09 18:11
PR incoming

**Comment by webknjaz** [comment] 2019-03-09 18:13
@jdavid this should fix it in a generic OS-independent way: https://github.com/libgit2/pygit2/pull/886. I don't have a windows machine to test it, though. So we'll have to wait for what AppVeyor CI has to say...

**Comment by webknjaz** [comment] 2019-03-15 21:56
@jdavid I saw the discussion in the related issue. Does this mean that we'll have to wait until the next patch release of libgit2?

**Comment by jdavid** [comment] 2019-03-16 08:23
There's something to fix in libgit2, but we don't have to wait for the next release.

We have to expose `GIT_OPT_ENABLE_STRICT_OBJECT_CREATION` and use it in the test to make it green.

**Comment by webknjaz** [comment] 2019-03-16 17:09
Oh, cool!

**Comment by jdavid** [comment] 2019-03-19 17:47
Done

**Closed by jdavid** 2019-03-19 17:47 UTC
