### ISSUE TITLE
config.set_multivar keeps adding new lines

### ISSUE THREAD

**Issue by pypingou** [libgit2/pygit2#373] opened 2014-05-28 07:55 UTC
Calling multiple times `repo_obj.config.set_multivar()` seems to keep adding empty lines to the configuration file

For example, before calling set_multivar:

```
[core]
    bare = true
    repositoryformatversion = 0
    filemode = true
[multimailhook]
    mailinglist = email
    environment = gitolite
```

after calling set_multivar:

```
[core]
    bare = true
    repositoryformatversion = 0
    filemode = true
[multimailhook]
    mailinglist = email
    environment = gitolite

```

If I call it one more time, then there are two empty lines at the bottom of the file

**Comment by tmr232** [comment] 2017-04-06 08:49
Is this still relevant? I cannot reproduce it (latest pygit2, Python 2.7.13, Windows 10 x64).

**Comment by jdavid** [comment] 2017-04-09 12:17
closing then, @pypingou please re-open if you still have the issue

**Closed by jdavid** 2017-04-09 12:17 UTC
