### ISSUE TITLE
Clone fails with GitError: Unexpected EOF

### ISSUE THREAD

**Issue by ovangle** [libgit2/pygit2#369] opened 2014-05-21 11:38 UTC
When trying to clone one of the repositories from the remote server, pygit2 is raising an `Early EOF` error when attempting to access the repository via ssh. 

The script I'm working on clones two repositories locally, the other is cloned without errors and both can be cloned from the command line via ssh. Both are cloned successfully over the http protocol.

**Comment by aspotashev** [comment] 2019-06-10 18:04
I can reproduce this *sometimes* here. clone_repository succeeds with about 20% chance.

**Comment by jdavid** [comment] 2020-10-04 08:59
Closing because this looks like a libgit2 bug that requires no action from pygit2. Apparently the same as https://github.com/libgit2/libgit2/issues/5279

**Closed by jdavid** 2020-10-04 08:59 UTC
