### ISSUE TITLE
pygit2-1.11.1 not compatible with libgit2-1.6.2

### ISSUE THREAD

**Issue by stumbles** [libgit2/pygit2#1198] opened 2023-03-07 12:00 UTC
lilbgit2-1.6.2, cffi-1.15.1 versions installed

running build_ext
generating cffi module 'build/temp.linux-x86_64-cpython-310/pygit2._libgit2.c'
creating build/temp.linux-x86_64-cpython-310
building 'pygit2._pygit2' extension
creating build/temp.linux-x86_64-cpython-310/src
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -O2 -march=native -pipe -Wp,-D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.10 -c src/blob.c -o build/temp.linux-x86_64-cpython-310/src/blob.o
In file included from src/diff.h:34,
                 from src/blob.c:30:
src/types.h:36:2: error: #error You need a compatible libgit2 version (1.5.x)
   36 | #error You need a compatible libgit2 version (1.5.x)
      |  ^~~~~
error: command '/var/lib/lunar/compilers/gcc' failed with exit code 1

**Comment by carlocab** [comment] 2023-03-12 18:18
Duplicate of #1193

**Comment by stumbles** [comment] 2023-03-12 18:33
I used a work around to install this by doing a;

make

then your standard python build/install using setup.py.

Using the make would do a similar thing as rustc, as in pulling down a whole lot of external files from the net I could not verify checksums, compiling in the source tree and moving on.

**Comment by jdavid** [comment] 2023-06-26 12:13
To use libgit2 1.6 you need pygit2 1.12
There is a version compatibility table here, https://www.pygit2.org/install.html#version-numbers

**Closed by jdavid** 2023-06-26 12:13 UTC
