### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by mcepl** [libgit2/pygit2#470] opened 2015-01-09 09:23 UTC
When running on RHEL-7 with libgit2-0.21.1-1.el7.x86_64 (and python-cffi-0.8.6-1.el7.x86_64 and libffi-3.0.13-11.el7.x86_64) I get this:

```
matej@mitmanek: pygit2 (master)$ python setup.py develop --user
running develop
Traceback (most recent call last):
  File "setup.py", line 197, in <module>
    cmdclass=cmdclass)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 51, in finalize_options
    easy_install.finalize_options(self)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 263, in finalize_options
    self._expand('install_dir','script_dir','build_directory','site_dirs')
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1363, in _expand
    config_vars = self.get_finalized_command('install').config_vars
  File "/usr/lib64/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 29, in finalize_options
    _install.finalize_options(self)
  File "/usr/lib64/python2.7/distutils/command/install.py", line 374, in finalize_options
    ('build_lib', 'build_lib'))
  File "/usr/lib64/python2.7/distutils/cmd.py", line 298, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 103, in finalize_options
    ffi, C = get_ffi()
  File "pygit2/_utils.py", line 85, in get_ffi
    ffi.cdef(header.read())
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 103, in cdef
    self._parser.parse(csource, override=override, packed=packed)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 166, in parse
    self._internal_parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 172, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 129, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 158, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "typedef int64_t git_time_t;"
:490: Multiple type specifiers with a type tag
matej@mitmanek: pygit2 (master)$
```

Not much reassuring.

**Comment by carlosmn** [comment] 2015-01-09 10:20
I cannot reproduce with CentOS 7 64-bit with cffi 0.8.6 and pycparser 2.10 which is what currently gets installed with pip. This is from an installation of libgit2 from source as libgit2 does not seem to be on the default package repos.

**Comment by mcepl** [comment] 2015-01-09 10:44
Upgraded libgit2 to the latest from Fedora Rawhide and the result is the same:
```
matej@mitmanek: pygit2 (master)$ python setup.py build
running build
Traceback (most recent call last):
  File "setup.py", line 197, in <module>
    cmdclass=cmdclass)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 103, in finalize_options
    ffi, C = get_ffi()
  File "pygit2/_utils.py", line 85, in get_ffi
    ffi.cdef(header.read())
  File "/usr/lib64/python2.7/site-packages/cffi/api.py", line 103, in cdef
    self._parser.parse(csource, override=override, packed=packed)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 166, in parse
    self._internal_parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 172, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 129, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib64/python2.7/site-packages/cffi/cparser.py", line 158, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "typedef int64_t git_time_t;"
:490: Multiple type specifiers with a type tag
matej@mitmanek: pygit2 (master)$ rpm -qf cffi
error: file /home/matej/archiv/knihovna/repos/pygit2/cffi: No such file or directory
matej@mitmanek: pygit2 (master)$ rpm -q cffi
package cffi is not installed
matej@mitmanek: pygit2 (master)$ rpm -qa \*cffi\*
python-cffi-0.8.6-1.el7.x86_64
matej@mitmanek: pygit2 (master)$ rpm -qa \*pycparser\*
python-pycparser-2.10-1.el7.noarch
matej@mitmanek: pygit2 (master)$ rpm -q libgit2
libgit2-0.21.3-1.el7.x86_64
matej@mitmanek: pygit2 (master)$
```

**Comment by StuartHa** [comment] 2015-01-12 01:36
I had the same issue and upgrading pycparser to 2.10 fixed the issue for me.

**Comment by mcepl** [comment] 2015-01-12 08:35
> I had the same issue and upgrading pycparser to 2.10 fixed the issue for me.

Let me just copy from the previous message:
```
matej@mitmanek: pygit2 (master)$ rpm -qa \*pycparser\*
python-pycparser-2.10-1.el7.noarch
matej@mitmanek: pygit2 (master)$
```

**Comment by 8427003** [comment] 2015-03-27 16:18
I want to cry ,when I install it on windows

**Comment by 8427003** [comment] 2015-04-01 11:15
when buiding  libgit2 and pygit2 ，  keep the build tools version the same

**Comment by pypingou** [comment] 2015-04-01 11:38
@8427003 how does this relate to this ticket which mentions RHEL-7 on its first post?

**Comment by 8427003** [comment] 2015-04-01 12:22
@pypingou  I'm so sorry, I think I solve “Fails to install on windows”

**Comment by anarcat** [comment] 2015-06-16 21:29
i confirm this doesn't build on Debian wheezy with pycparser 2.7 but works after `pip upgrade pycparser`.

**Comment by jmdcal** [comment] 2015-07-08 16:05
I needed to : 
```sudo pip install --upgrade pycparser```

on fc20

**Comment by jdavid** [comment] 2019-03-19 17:58
Closing this, pygit2 should be easier to install in Linux now we have manylinux wheels.

Regarding pycparser it works with 2.17 but it doesn't with 2.18 and 2.19, issue #846

**Closed by jdavid** 2019-03-19 17:58 UTC
